-- Criação do banco de dados
CREATE DATABASE IF NOT EXISTS FilmesDB;

-- Seleciona o banco de dados
USE FilmesDB;

-- Criação da tabela de filmes
CREATE TABLE IF NOT EXISTS filmes (
    id INT AUTO_INCREMENT PRIMARY KEY,     -- Identificador único
    titulo VARCHAR(255) NOT NULL,          -- Título do filme
    sinopse TEXT,                          -- Sinopse do filme
    capa VARCHAR(255),                     -- URL da capa do filme
    url_filme VARCHAR(255) NOT NULL,       -- URL do filme
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP -- Data de criação do registro
);


-- INSERT INTO filmes (id,titulo, sinopse, capa, url_filme) VALUES (0,'titulo','sinopse','capas/rectangle5.png','https://embed.embedplayer.site/');

INSERT INTO filmes (titulo, sinopse, capa, url_filme) VALUES ('Camponeses','Século XIX. Jagna, uma jovem de família humilde, está determinada a forjar seu próprio destino no pequeno vilarejo polonês onde vive.','capas/camponeses.jpg','https://embed.embedplayer.site/tt10651230');
INSERT INTO filmes (titulo, sinopse, capa, url_filme) VALUES ('A Chorona','O general aposentado, Enrique, finalmente enfrenta julgamento pelo massacre genocida de milhares de maias décadas atrás. Enquanto uma horda de manifestantes raivosos ameaça invadir seu lar opulento, as mulheres da casa – sua esposa arrogante, filha em conflito e neta precoce – refletem sobre sua responsabilidade de proteger Enrique, errático e senil, contra as verdades devastadoras que são reveladas publicamente enquanto começam a sentir uma força sobrenatural em busca de vingança por seus crimes. Enquanto isso, grande parte dos empregados da família foge, deixando apenas a governanta leal Valeriana até que uma misteriosa jovem indígena chega…','capas/chorona.jpg','https://embed.embedplayer.site/tt10767168');
INSERT INTO filmes (titulo, sinopse, capa, url_filme) VALUES ('O Intruso','Após largar o trabalho de policial no departamento de apreensão de drogas, uma mulher decide permanecer em casa e cuidar dos dois filhos. Um dia, ao testemunhar um acidente de carro, ela deixa a vítima entrar em sua casa para ser ajudada. Ela mal sabe que este é, na verdade, um prisoneiro que escapou da prisão, e simulou o acidente para se aproximar da antiga policial. Em seguida, este homem sequestra a família e aterroriza as crianças.','capas/ointruso.jpg','https://embed.embedplayer.site/tt2011159');
INSERT INTO filmes (titulo, sinopse, capa, url_filme) VALUES ('Super-Herói: O Filme','Rick Riker é um estudante comum do colegial. Porém, ao ser mordido por uma libélula geneticamente modificada ganha superpoderes. Agora sua missão é proteger a cidade das mãos do malvado Hourglass, que suga a vida de suas vítimas.','capas/superheros.jpg','https://embed.embedplayer.site/tt0426592');
INSERT INTO filmes (titulo, sinopse, capa, url_filme) VALUES ('O Lobo de Wall Street','Durante seis meses, Jordan Belfort (Leonardo DiCaprio) trabalhou duro em uma corretora de Wall Street, seguindo os ensinamentos de seu mentor Mark Hanna (Matthew McConaughey). Quando finalmente consegue ser contratado como corretor da firma, acontece o Black Monday, que faz com que as bolsas de vários países caiam repentinamente. Sem emprego e bastante ambicioso, ele acaba trabalhando para uma empresa de fundo de quintal que lida com papéis de baixo valor, que não estão na bolsa de valores. É lá que Belfort tem a idéia de montar uma empresa focada neste tipo de negócio, cujas vendas são de valores mais baixos mas, em compensação, o retorno para o corretor é bem mais vantajoso. Ao lado de Donnie (Jonah Hill) e outros amigos dos velhos tempos, ele cria a Stratton Oakmont, uma empresa que faz com que todos enriqueçam rapidamente e, também, levem uma vida dedicada ao prazer.','capas/olobodewall.jpg','https://embed.embedplayer.site/tt0993846');
INSERT INTO filmes (titulo, sinopse, capa, url_filme) VALUES (' O Dilema das Redes','Especialistas em tecnologia e profissionais da área fazem um alerta: as redes sociais podem ter um impacto devastador sobre a democracia e a humanidade.','capas/redessociais.jpg','https://embed.embedplayer.site/tt11464826');
INSERT INTO filmes (titulo, sinopse, capa, url_filme) VALUES ('Camponeses','Século XIX. Jagna, uma jovem de família humilde, está determinada a forjar seu próprio destino no pequeno vilarejo polonês onde vive.','capas/camponeses.jpg','https://embed.embedplayer.site/tt10651230');
INSERT INTO filmes (titulo, sinopse, capa, url_filme) VALUES ('A Chorona','O general aposentado, Enrique, finalmente enfrenta julgamento pelo massacre genocida de milhares de maias décadas atrás. Enquanto uma horda de manifestantes raivosos ameaça invadir seu lar opulento, as mulheres da casa – sua esposa arrogante, filha em conflito e neta precoce – refletem sobre sua responsabilidade de proteger Enrique, errático e senil, contra as verdades devastadoras que são reveladas publicamente enquanto começam a sentir uma força sobrenatural em busca de vingança por seus crimes. Enquanto isso, grande parte dos empregados da família foge, deixando apenas a governanta leal Valeriana até que uma misteriosa jovem indígena chega…','capas/chorona.jpg','https://embed.embedplayer.site/tt10767168');
INSERT INTO filmes (titulo, sinopse, capa, url_filme) VALUES ('O Intruso','Após largar o trabalho de policial no departamento de apreensão de drogas, uma mulher decide permanecer em casa e cuidar dos dois filhos. Um dia, ao testemunhar um acidente de carro, ela deixa a vítima entrar em sua casa para ser ajudada. Ela mal sabe que este é, na verdade, um prisoneiro que escapou da prisão, e simulou o acidente para se aproximar da antiga policial. Em seguida, este homem sequestra a família e aterroriza as crianças.','capas/ointruso.jpg','https://embed.embedplayer.site/tt2011159');
INSERT INTO filmes (titulo, sinopse, capa, url_filme) VALUES ('Super-Herói: O Filme','Rick Riker é um estudante comum do colegial. Porém, ao ser mordido por uma libélula geneticamente modificada ganha superpoderes. Agora sua missão é proteger a cidade das mãos do malvado Hourglass, que suga a vida de suas vítimas.','capas/superheros.jpg','https://embed.embedplayer.site/tt0426592');
INSERT INTO filmes (titulo, sinopse, capa, url_filme) VALUES ('O Lobo de Wall Street','Durante seis meses, Jordan Belfort (Leonardo DiCaprio) trabalhou duro em uma corretora de Wall Street, seguindo os ensinamentos de seu mentor Mark Hanna (Matthew McConaughey). Quando finalmente consegue ser contratado como corretor da firma, acontece o Black Monday, que faz com que as bolsas de vários países caiam repentinamente. Sem emprego e bastante ambicioso, ele acaba trabalhando para uma empresa de fundo de quintal que lida com papéis de baixo valor, que não estão na bolsa de valores. É lá que Belfort tem a idéia de montar uma empresa focada neste tipo de negócio, cujas vendas são de valores mais baixos mas, em compensação, o retorno para o corretor é bem mais vantajoso. Ao lado de Donnie (Jonah Hill) e outros amigos dos velhos tempos, ele cria a Stratton Oakmont, uma empresa que faz com que todos enriqueçam rapidamente e, também, levem uma vida dedicada ao prazer.','capas/olobodewall.jpg','https://embed.embedplayer.site/tt0993846');
INSERT INTO filmes (titulo, sinopse, capa, url_filme) VALUES (' O Dilema das Redes','Especialistas em tecnologia e profissionais da área fazem um alerta: as redes sociais podem ter um impacto devastador sobre a democracia e a humanidade.','capas/redessociais.jpg','https://embed.embedplayer.site/tt11464826');
